[package]
name = "goto-label"
version = "0.1.0"
edition = "2021"
rust-version = "1.59.0"

[dependencies]

[profile.release]
# If you use this crate as a dependency, you should add this line in your Cargo.toml 
# otherwise your code WILL segfault
opt-level = 1
